CLI: disable color output by default if NO_COLOR set or escape codes not supported
Vexu/arocc pull request #335
Opened 2022-07-07 19:35 UTC by ehaas

2022-07-07 19:42 UTC, ehaas commented
My intention here was to prevent `--verbose-ast` from using color when redirected to a file / `NO_COLOR` set, but I see now that there is also some logic in `Diagnostics.init` - since one is using stdout and the other stderr, it seems like we'd actually need two flags (since `Tree.dump` is just using `diag.color`)

2022-07-07 20:16 UTC, Vexu commented
> On second thought, maybe the right approach here is just to temporarily override `comp.diag.color` in the `comp.verbose_ast` check, when dumping the Tree (if stdout does not support color)?

Sounds good to me.

2022-07-08 06:37 UTC, ehaas commented
Hopefully not too big of a change - I wanted to make it so the `NO_COLOR` env var can be overridden by command-line flags. I also wanted the default value of `Diagnostics.color` in the library not to depend on the existence of file descriptors or environment variables

2022-07-08 06:57 UTC, Vexu requested changes

2022-07-08 06:57 UTC, Vexu commented on src/util.zig
> +pub fn environmentDisabledColor() bool {
This does the same as `std.process.hasEnvVarConstant`.

2022-07-08 06:57 UTC, Vexu commented on src/Compilation.zig
> +color_diagnostics: enum {
This should be a local variable in `main.zig`.

2022-07-08 06:57 UTC, Vexu commented on src/main.zig
> +        const color = comp.shouldUseColor(util.fileSupportsColor(stdout), util.environmentDisabledColor());
```suggestion
        const color = comp.diag.color and util.fileSupportsColor(stdout);
```

2022-07-09 03:25 UTC, ehaas commented
For the variable shadowing error - would you rather rename the `err` function in various modules, or rename the error capture?

2022-07-09 08:07 UTC, Vexu commented
> For the variable shadowing error - would you rather rename the `err` function in various modules, or rename the error capture?

Oh right, its the bugs I filed getting fixed. I decided to fix it by renaming the captures since I've done that before with `if`s on error unions and there are fewer captures than calls to the `err` functions.

2022-07-09 08:12 UTC, merged