Check argument size on static array parameters
Vexu/arocc pull request #742
Opened 2024-08-03 18:39 UTC by wrongnull

Closes https://github.com/Vexu/arocc/issues/349

2024-08-04 10:43 UTC, Vexu requested changes

2024-08-04 10:43 UTC, Vexu commented on src/aro/Parser.zig
> +            if (arg.ty.data == .array and arg.ty.data.array.*.len < p_ty.data.array.*.len) {
This should use `arrayLen` instead of making the union tagged.

2024-08-04 10:43 UTC, Vexu commented on src/aro/Parser.zig
> +                try p.errExtra(.array_argument_too_small, param_tok, extra);
Clang also adds a `callee declares array parameter as static here` note. You should be able to do the same with `params[arg_count].name_tok`.

2024-08-04 10:43 UTC, Vexu commented on src/aro/Type.zig
> +statically_sized_array: bool = false,
`static_array` specifier exists but is seemingly unused currently. Could you try using that instead?

(Apparently it was only used for three days between c35d5c22f7adc314202c5dcd220d88d6ff7d068d and 9b4daaa8647d8ea7c24ed6edae66a32433fb4ba6)

2024-08-05 06:06 UTC, wrongnull commented
@Vexu all the desired changes have been made

2024-08-05 09:10 UTC, merged